### ISSUE TITLE
Espresso test and error

### ISSUE THREAD

**Issue by hannesa2** [Malinskiy/action-android#18]
I run this sucessful

```
      - name: Run instrumentation tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.0.3
        with:
          cmd: ./gradlew connectedAndroidTest --stacktrace
          api: 25
          tag: default
          abi: x86
```
and when some Espresso test are unsuccessful, the  action is still successful

How to break build on failed Espresso tests ?
