### ISSUE TITLE
adb command not found error

### ISSUE THREAD

**Issue by pravinyo** [Malinskiy/action-android#22]
I am trying to run instrumentation test on Ubuntu 18.

Here is the yml file code:

```
on:
  push:
    branches:
      - '*'
      - '!master'
      - '!release*'

jobs:
  instrumentationJob:
    name: Run Instrumentation Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - uses: malinskiy/action-android/install-sdk@release/0.0.6
      - run: adb devices
      - run: echo $ANDROID_HOME
      
      - uses: malinskiy/action-android/emulator-run-cmd@release/0.0.6
        with:
          cmd: ./gradlew connectedDebugAndroidTest
          api: 25
          tag: default
          abi: x86
      - name: Save logcat output
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: logcat
          path: artifacts/logcat.log
```

Here is the error, I am getting:

```
adb devices
  shell: /bin/bash -e {0}
  env:
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.252/x64
    JAVA_HOME_8.0.252_x64: /opt/hostedtoolcache/jdk/8.0.252/x64
    ANDROID_HOME: /home/runner/android-sdk
    ANDROID_SDK_ROOT: /home/runner/android-sdk
    ANDROID_SDK_HOME: /home/runner/android-sdk/sdk_home
    PATH: :/home/runner/android-sdk/bin:/home/runner/android-sdk/tools:/opt/hostedtoolcache/jdk/8.0.252/x64/bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin/tools/bin:/opt/hostedtoolcache/jdk/8.0.252/x64/bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin/platform-tools/bin
/home/runner/work/_temp/f9b044b4-656b-48be-bf0f-d3fa658ce199.sh: line 1: adb: command not found
##[error]Process completed with exit code 127.
```
What i missed here?
