### ISSUE TITLE
Allow caching the SDK

### ISSUE THREAD

**Issue by TurpIF** [Malinskiy/action-android#26]
Hello,

After few runs, I saw that setup of the Android SDK may takes time. I already saw taking a sdkmanager command taking up to 10 minutes.

In order to improve this timing, one can use an `actions/cache`:
```
- name: Store Android SDK
   uses: actions/cache@v2
   with:
     path: {{ env.ANDROID_HOME }}
     key: ${{ runner.os }}-android-${{ hashFiles('**/*.gradle*') }}
     restore-keys: ${{ runner.os }}-android-
```

But this action always remove every traces of a previously setup SDK (why btw ?)

Would it be possible to add an option to check for an existing SDK that was setup by your action and to keep it instead of erasing it and redownloading everything ?
Also, to ease the caching, and ANDROID_HOME env variable could be published by the action.
