### ISSUE TITLE
`tr` command not found on `macOs` builds

### ISSUE THREAD

**Issue by zegnus** [Malinskiy/action-android#3]
When using the following workflow

```
name: Android CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
      with:
        depth: 1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install Android SDK
      uses: malinskiy/action-android/install-sdk@release/0.0.2
    - name: Instrumentation Tests
      uses: malinskiy/action-android/emulator-run-cmd@release/0.0.2      
      with:
        cmd: ./team-props/instrumentation.sh
        api: 21
        tag: google_apis
        abi: x86
```

then in the command line I can see the following error:
```
/system/bin/sh: tr: not found
Sleeping for 1s
/Users/runner/android-sdk/platform-tools/adb shell getprop sys.boot_completed | tr -d '
```

it times out at the end and the emulator is correctly booted:
```
Timeout waiting for emulator to boot. Exiting
booted=false
emulator started and booted
```
