### ISSUE TITLE
Gradle Managed Devices

### ISSUE THREAD

**Issue by hannesa2** [Malinskiy/action-android#76]
I tried to use Gradle Managed Devices https://developer.android.com/studio/test/gradle-managed-devices
```

      - name: Run instrumentation tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.4
        with:
          cmd: ./gradlew nexusOneApi30DebugAndroidTest
```

```
    testOptions {
        managedDevices {
            devices {
                nexusOneApi30(com.android.build.api.dsl.ManagedVirtualDevice) {
                    // A lower resolution device is used here for better emulator performance
                    device = "Nexus One"
                    apiLevel = 30
                    // Also use the AOSP ATD image for better emulator performance
                    // The androidx.test screenshot APIs will automatically enable hardware rendering to take a screenshot
                    systemImageSource = "aosp-atd"
                }
            }
        }
    }

```but I run into 

```
Execution failed for task ':sample:nexusOneApi30Setup'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.ManagedDeviceSetupTask$ManagedDeviceSetupRunnable
   > java.lang.IllegalStateException: Gradle was not able to complete device setup for: dev30_aosp_atd_x86_Nexus_One
     This could be due to having insufficient resources to provision the number of
     devices requested. Try running the test again and request fewer devices or
     fewer shards.
```

Does someone knows, how to use Gradle Managed Devices with Github actions ?
