### ISSUE TITLE
Impossible to install older command-line tools, always `latest` is downloaded

### ISSUE THREAD

**Issue by bartekpacia** [Malinskiy/action-android#86]
I need to install Command-Line Tools v8, the last version comaptible with Java 8.

I found the right URL, but even when I pass it, I still get command-line tools `latest`, which require JDK17:

```yaml
- name: Set up Android SDK
  uses: malinskiy/action-android/install-sdk@release/0.1.7
  with:
    url: https://dl.google.com/android/repository/commandlinetools-linux-9123335_latest.zip
    # Above URL points to Command Line Tools v8.0 - the last version compatible with Java 8
    # Found via https://stackoverflow.com/a/75763391/7009800
    # Another useful website: https://androidsdkmanager.azurewebsites.net/cmdline-tools.html
```

see workflow run: https://github.com/mobile-dev-inc/maestro/actions/runs/10221637495/job/28284879896?pr=1837
